os:
  - linux

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - build-essential
      - git
      - libc6-i386
      - time

git:
  depth: 5

language: c

install:
  - make arm_sdk_install

before_script:
  - make arm_sdk_version

script:
  - make

cache:
  directories:
  - downloads
  - tools
